# Generated by Django 3.0.8 on 2020-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity_details', '0007_useractivity_userdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivity',
            table='user_activity',
        ),
        migrations.AlterModelTable(
            name='userdetail',
            table='user_details',
        ),
    ]
