# Generated by Django 3.0.8 on 2020-07-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity_details', '0002_auto_20200707_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
