# Generated by Django 3.0.8 on 2020-07-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity_details', '0003_auto_20200707_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
