# Generated by Django 3.0.8 on 2020-07-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity_details', '0005_useractivity_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
